name: dart_converter
description: A tool for image conversion.
version: 1.0.0

environment:
  sdk: ^3.4.3

dependencies:
  dart_prompter_mj: ^1.0.0
  image: ^4.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
